# Generated by Django 5.0 on 2024-02-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofile_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_code',
        ),
    ]
